### ISSUE TITLE
It'll caused scroll jerky

### ISSUE THREAD

**Issue by kimlet** [uxcam/flutter-plugin#23]
When I enabled this SDK in my project, I found it was jerky in any scrollable view when I scrolled slowly. Everything is perfect when I remove this plugin.

**Comment by gabrieluxcam** [comment]
Hello @kimlet thanks for bringing this up, the information provided will be extremely helpful. 

As a side note, it would be ideal if you could change the startup method to the updated one shown [here](https://developer.uxcam.com/docs/flutter). 

We will keep you posted on any updates. Thanks!

**Comment by kimlet** [comment]
> 

Hi @gabrieluxcam 
There are nothing changes when I change the startup method to
`FlutterUxcam.optIntoSchematicRecordings();`
`FlutterUxConfig config = FlutterUxConfig(
      userAppKey: "xxxxxxxxxxx",
      enableAutomaticScreenNameTagging: true,
    );`
`FlutterUxcam.startWithConfiguration(config);`

**Comment by mahmoudatef955** [comment]
I have the same problem, once I enabled this SDK in my project I noticed stutter in scrolling and a huge impact on app performance, and it is more noticeable on android devices.

**Comment by justincbeck** [comment]
I am also seeing this behavior. I think I'll need to switch to a different screen recording library.

**Comment by justincbeck** [comment]
This isn't just an Android issue. Is someone looking into this?

**Comment by DFDIEGOH** [comment]
Hi everyone! First of all I just wanted to apologize for the delay in this regard. But would it be possible to use the latest version of the Flutter SDK which is 2.4.6? This should be fixed already in this version.

**Comment by OgunwoleOluwatobi** [comment]
Hello @DFDIEGOH 
This issue still persists on the latest version. Scroll stutters still appears when scrolling quickly.

**Comment by SamerOrfali22** [comment]
the issue still for now
