### ISSUE TITLE
Performance issue on iOS when using UXCAM plugin with Google Maps Flutter (UXCam version 2.3.0)

### ISSUE THREAD

**Issue by aovooyov** [uxcam/flutter-plugin#27]
We have discovered a performance issue on iOS when using the Maps plugin and the UXCAM analytics tool. 
When UXCAM version 2.3.0 is running, the map interface becomes very laggy, making it impossible to use the app properly. We are using the google_maps_flutter 2.2.5 plugin to display the maps.

Steps to reproduce:
Launch the app with Maps plugin and UXCAM version 2.3.0 on iOS
Try to move or zoom in/out the map
Notice that the map interface becomes laggy

Expected behavior: 
The map should be smooth and responsive, even when using the Maps plugin and UXCAM version 2.3.0 on iOS.

Actual behavior: 
The map interface becomes laggy on iOS, making it impossible to use the app properly when using UXCAM version 2.3.0. However, we have found that there are no performance issues when using UXCAM version 2.2.2 on iOS.

Additional information: 
We have tested the app on different iOS devices and found that the issue occurs on all devices running UXCAM version 2.3.0, but not on devices running UXCAM version 2.2.2.

Versions:
flutter_uxcam 2.3.0
google_maps_flutter 2.2.5
Flutter version 3.3.10
Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
Engine revision 3316dd8728
Dart version 2.18.6
DevTools version 2.15.0

https://user-images.githubusercontent.com/3726001/228025445-a5140cab-2225-4798-8eb6-9903caa789d1.mov

On version Flutter 3.7.8 the same effect

**Comment by gabrieluxcam** [comment]
Hello @myredsocks Gabriel here. 

I'm happy to let you know we've now released Flutter SDK v2.4.0, which contains a fix for your current issue. 

It'd be extremely helpful if you can upgrade and let us know if anything. Apologies for the hassle this may have caused, thanks in advance!

**Comment by Wolfikus** [comment]
> Hello @myredsocks Gabriel here.
> 
> I'm happy to let you know we've now released Flutter SDK v2.4.0, which contains a fix for your current issue.
> 
> It'd be extremely helpful if you can upgrade and let us know if anything. Apologies for the hassle this may have caused, thanks in advance!

Hello! We still experiencing same issue with memory leak, also reported in https://github.com/uxcam/flutter-plugin/issues/28

StackTrace attached

[62751283f37ff98f4a8da99a0ad0ae2e_crash_session_8d017b96e55e4022ab44eee40496e24d_DNE_1_v2_stacktrace.txt](https://github.com/uxcam/flutter-plugin/files/11592905/62751283f37ff98f4a8da99a0ad0ae2e_crash_session_8d017b96e55e4022ab44eee40496e24d_DNE_1_v2_stacktrace.txt)

**Comment by gabrieluxcam** [comment]
Hello @Wolfikus memory issues have been fixed on 2.4.1 which has released a couple of days ago, could you try giving it a go? As the code that is crashing in that stack trace should not run in latest sdk. If it indeed happens on the latest SDK, could you let me know the iOS version in which it is crashing? Thanks

**Comment by myredsocks** [comment]
> Hello @Wolfikus memory issues have been fixed on 2.4.1 which has released a couple of days ago, could you try giving it a go? As the code that is crashing in that stack trace should not run in latest sdk. If it indeed happens on the latest SDK, could you let me know the iOS version in which it is crashing? Thanks

OS version: iOS 16.2.0

**Comment by gabrieluxcam** [comment]
Hello @myredsocks Flutter SDK 2.4.2 comes with several fixes, among them some native ones affecting Flutter, could it be possible to test it our and monitor how it behaves? Thanks!

**Comment by DFDIEGOH** [comment]
Closed due to inactivity
